// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Mobile platforms not configured - WEB ONLY app
    throw UnsupportedError(
      'DefaultFirebaseOptions are configured for WEB ONLY. '
      'This is a web-first application.',
    );
  }

  // WEB-ONLY Configuration
  // TEMPORARY: Hardcoded values for testing - WILL BE SECURED LATER
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbNIrijtZeq3uvlqOU522l3nzs6_uV4',
    appId: '1:878295516341:web:f267412e0c35aaf80beafc',
    messagingSenderId: '878295516341',
    projectId: 'clinicadvisor-1a911',
    authDomain: 'clinicadvisor-1a911.firebaseapp.com',
    storageBucket: 'clinicadvisor-1a911.firebasestorage.app',
  );
} 