// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Gerçek Firebase Config - Firebase Console'dan alındı
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBozx_5HK10W-H29ya6UfX41ASW-75H3Q4',
    appId: '1:878295516341:web:72d945223b7d74760beafe', 
    messagingSenderId: '878295516341',
    projectId: 'clinicadvisor-1a911',
    authDomain: 'clinicadvisor-1a911.firebaseapp.com',
    storageBucket: 'clinicadvisor-1a911.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBozx_5HK10W-H29ya6UfX41ASW-75H3Q4',
    appId: '1:878295516341:android:ANDROID_APP_ID_HERE',
    messagingSenderId: '878295516341',
    projectId: 'clinicadvisor-1a911',
    storageBucket: 'clinicadvisor-1a911.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBozx_5HK10W-H29ya6UfX41ASW-75H3Q4',
    appId: '1:878295516341:ios:IOS_APP_ID_HERE',
    messagingSenderId: '878295516341',
    projectId: 'clinicadvisor-1a911',
    iosBundleId: 'com.clinicadvisor.clinicadvisorV2',
    storageBucket: 'clinicadvisor-1a911.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBozx_5HK10W-H29ya6UfX41ASW-75H3Q4',
    appId: '1:878295516341:macos:MACOS_APP_ID_HERE',
    messagingSenderId: '878295516341',
    projectId: 'clinicadvisor-1a911',
    iosBundleId: 'com.clinicadvisor.clinicadvisorV2',
    storageBucket: 'clinicadvisor-1a911.firebasestorage.app',
  );
} 